name: Continuous Integration
on:
  push:
    branches:
      - main
  pull_request:

env:
  NEXT_PUBLIC_ALCHEMY_KEY: ${{ secrets.NEXT_PUBLIC_ALCHEMY_KEY }}
  ADMIN_PRIVATE_KEY: ${{ secrets.ADMIN_PRIVATE_KEY }}
  MNEMONIC: ${{ secrets.MNEMONIC }}

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        shell: bash

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: ^7.2.1
      - name: Setup Node v16
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'pnpm'

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Add NPM_TOKEN
        run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Run Tests
        run: pnpm -r --filter=@soundxyz/protocol test
